"use client";

import { HeroSection } from "@/components/miforge/HeroSection";
import { PricingTierCard } from "@/components/miforge/PricingTierCard";
import { CapacityMeter } from "@/components/miforge/CapacityMeter";
import { GradientHeadline } from "@/components/shared/GradientHeadline";
import { MonoLabel } from "@/components/shared/MonoLabel";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { mockPricingTiers } from "@/lib/supabase/mocks";
import Link from "next/link";

const faqs = [
  { q: "How does uplift share work?", a: "Uplift share is calculated on measurable outcomes attributable to your factory's agents — revenue recovered, cost savings, reactivated customers, and verified price improvements. We agree on measurement methodology during scoping." },
  { q: "Can I cancel my retainer?", a: "Yes. After your tier's minimum commitment (1-6 months depending on tier), the retainer is month-to-month. Cancel with 30 days notice." },
  { q: "What's included in the forge fee?", a: "Everything needed to build your factory: scoping, agent development, integration wiring, brand voice calibration, testing, and initial deployment support." },
  { q: "Do I own what my agents produce?", a: "Yes. All outputs generated by your factory are your intellectual property. No lock-in, no hidden clauses." },
  { q: "What if I need more agents later?", a: "Add agents anytime. Standard additions take 1-2 weeks. Bespoke agents take 2-4 weeks. Priced individually based on complexity." },
  { q: "What happens if an agent underperforms?", a: "Weekly optimization is standard. If an agent consistently underperforms after 30 days of tuning, we replace it at no additional forge fee." },
  { q: "Is there a free trial?", a: "No free trial, but every factory operates in demo mode before activation. You see exactly what you're getting before you pay." },
  { q: "What payment methods do you accept?", a: "We process payments through Paddle (cards, Apple Pay, Google Pay) and GoCardless (direct bank debit for retainers). Both are PCI-compliant." },
];

export default function PricingPage() {
  const currentMonth = new Date().toLocaleString("default", { month: "long", year: "numeric" });

  return (
    <>
      <HeroSection
        headline="Forging isn't cheap. It's not supposed to be."
        subhead="You don't buy this. You commission it. Every quote is bespoke. Every factory is forged for one operator."
      />

      {/* Hybrid Model Explained */}
      <section className="w-full bg-milyfe-surface py-20 md:py-[120px]">
        <div className="mx-auto max-w-5xl px-6">
          <h2 className="text-center font-fraunces text-3xl text-milyfe-text mb-12">The Hybrid Model</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div className="rounded-xl border border-milyfe-border bg-milyfe-bg p-6 text-center">
              <MonoLabel className="block mb-3">FORGE FEE (ONE-TIME)</MonoLabel>
              <p className="text-sm text-milyfe-text-muted">The build. Your factory is architected, agents calibrated, systems wired. Paid once, at activation.</p>
            </div>
            <div className="rounded-xl border border-milyfe-border bg-milyfe-bg p-6 text-center">
              <MonoLabel className="block mb-3">OPERATING RETAINER (MONTHLY)</MonoLabel>
              <p className="text-sm text-milyfe-text-muted">The heartbeat. Agents stay running, tuned, and supported. Cancel anytime after your tier&apos;s minimum.</p>
            </div>
            <div className="rounded-xl border border-milyfe-border bg-milyfe-bg p-6 text-center">
              <MonoLabel className="block mb-3">UPLIFT SHARE (PERFORMANCE)</MonoLabel>
              <p className="text-sm text-milyfe-text-muted">The alignment. We take a percentage of measurable outcomes we produce. If your factory doesn&apos;t win, neither do we.</p>
            </div>
          </div>
          <p className="text-center text-milyfe-gradient font-fraunces text-lg">
            Small to start. Predictable to run. We only win big when you win big.
          </p>
        </div>
      </section>

      {/* Capacity Meter */}
      <CapacityMeter month={currentMonth} slotsTotal={5} slotsUsed={2} />

      {/* Pricing Tiers */}
      <section className="w-full bg-milyfe-bg py-20">
        <div className="mx-auto max-w-6xl px-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {mockPricingTiers.map((tier) => (
              <PricingTierCard key={tier.id} tier={tier} featured={tier.featured} />
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="w-full bg-milyfe-surface py-16">
        <div className="mx-auto max-w-3xl px-6">
          <h2 className="text-center font-fraunces text-2xl text-milyfe-text mb-8">Questions</h2>
          <Accordion type="single" collapsible>
            {faqs.map((faq, i) => (
              <AccordionItem key={i} value={`faq-${i}`}>
                <AccordionTrigger className="text-left text-milyfe-text">{faq.q}</AccordionTrigger>
                <AccordionContent className="text-milyfe-text-muted">{faq.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* Closing CTA */}
      <section className="w-full bg-milyfe-bg py-24">
        <div className="mx-auto max-w-3xl px-6 text-center">
          <GradientHeadline size="section">Every quote is bespoke. Every factory is forged for one operator.</GradientHeadline>
          <div className="mt-8">
            <Link href="/miforge/bespoke"><Button variant="gradient" size="lg">Request a Forge</Button></Link>
            <p className="mt-4 font-mono text-xs text-milyfe-text-muted">miforge@milyfe.fun</p>
          </div>
        </div>
      </section>
    </>
  );
}
